name: tic_tac_toe
description: "Tic Tac Toe Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0


  # Google Sign In
  google_sign_in: ^6.2.1

  # State Management
  provider: ^6.1.2

  # Shared Preferences
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  generate: true
  assets:
  - l10n/